charts/s3gw/Chart.yaml
charts/s3gw/templates/ingress-traefik.yaml

Fixes: https://github.com/aquarist-labs/s3gw-charts/issues/9

Removed ingressClassName specification

---

CHANGELOG.md
charts/s3gw/Chart.yaml
charts/s3gw/values.yaml

- s3gw image set to v0.3.0 in values.yaml

Release 0.3.0

---

.editorconfig
charts/s3gw/Chart.yaml
charts/s3gw/README.md
charts/s3gw/values.yaml

Fix typos in documentation and code.

---

charts/s3gw/Chart.yaml
charts/s3gw/values.yaml

Version 0.4.0

---

.github/pull_request_template.md
.gitignore

This PR implements a Pull Request template. It was proposed [in this PR](https://github.com/aquarist-labs/s3gw/pull/97).
https://github.com/aquarist-labs/s3gw/issues/22
about this update.
Signed-off-by: Jesus HM <jherman@suse.com>

Adds PR template to Charts repository

---

charts/s3gw/Chart.yaml
charts/s3gw/values.yaml

Bump container versions to v0.5.0

version bump: v0.5.0

---

README.md
charts/s3gw/README.md

This PR adds the install information for Rancher and removes the duplicated information already found [here](https://s3gw-docs.readthedocs.io/en/latest/helm-charts/). 
https://github.com/aquarist-labs/s3gw/issues/81
Signed-off-by: Jesus HM <jherman@suse.com>

Adds information for Rancher

---

artifacthub-repo.yml

Claim ownership of artifacthub repo by means of artifacthub-repo.yml

chart release: claim ownership on artifacthub

---

charts/s3gw/Chart.yaml

Bump container versions to v0.6.0
Signed-off-by: Jesus HM <jherman@suse.com>

Bump container versions to v0.6.0

---

CHANGELOG.md

Signed-off-by: Jesus HM <jherman@suse.com>

Update changelog dates

---

CHANGELOG.md

This reverts commit a40acca552fd5d3b627b1a968d68f8108c1abe24, reversing changes made to 4928463ddf5c5bf10e476b2e8de5aa202c7e8ce6.

Revert "Merge pull request #50 from 0xavi0/changelog-0.7.0"

---

charts/s3gw/Chart.yaml

Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>

Update version to 0.7.0

---

CHANGELOG.md
charts/s3gw/templates/ingress-traefik.yaml

Fixes: https://github.com/aquarist-labs/s3gw/issues/188

charts: The OPTIONS method is missing in the Traefik CORS config.

---

.github/workflows/lint.yaml
.github/workflows/release.yaml
.pre-commit-config.yaml
CHANGELOG.md
README.md
charts/s3gw/README.md
charts/s3gw/app-readme.md
tests/private-registry.yaml

- Lint markdown and yaml files for syntax errors
- Test templates against non-default configurations for correct syntax
- Update readmes to reflect latest changes in release
- Separate testing and release workflow, make workflow callable

ci: lint and test

---

charts/s3gw/Chart.yaml

Bump chart version to 0.8.0.

---

CHANGELOG.md
charts/s3gw/Chart.yaml

Signed-off-by: Volker Theile <vtheile@suse.com># Describe your changes

Merge `v0.8.0` branch into `main`.

---

.github/workflows/release.yaml

ci: fix typo in release workflow

---

.github/workflows/lint.yaml
.github/workflows/release.yaml
charts/s3gw/Chart.yaml

bump version 0.9.0

---

CHANGELOG.md

bump version 0.9.0 into CHANGELOG.md

bump version 0.9.0 into CHANGELOG.md

---

CHANGELOG.md

merge main with release branch v0.9.0

Merge w v0.9.0

---

README.md

- Add Slack badge and link to channel
- Remove broken workflow badge
- Add description based on introductory blogpost

docs: rework charts readme

---

README.md
charts/s3gw/Chart.yaml

- Release v0.10.0
- Add license text to readme

release: v0.10.0

---

CHANGELOG.md

Fix changelog chapters for v0.10.0 release

release: fix changelog for v0.10.0

---

README.md
charts/s3gw/README.md

- Enhance readme file for artifacthub.io by adding description, license information and removing unnecessary instructions
- Fix link pointing to s3gw github repo in the top level readme
Fixes: aquarist-labs/s3gw#224

docs: enhance description for artifacthub.io

---

charts/s3gw/Chart.yaml

release: version 0.11.0

---

charts/s3gw/Chart.yaml

release: v0.12.0

---

charts/s3gw/Chart.yaml

release: v0.13.0

---

charts/s3gw/Chart.yaml

Release 0.14.0
Signed-off-by: Marcel Lauhoff <marcel.lauhoff@suse.com>

Release 0.14.0

---

.github/workflows/lint.yaml
charts/s3gw/templates/chart-validation.yaml
charts/s3gw/values.yaml
tests/private-registry.yaml

- Change default domain to the stadard `example.com`, instead of the more esoteric `.howdoi.website`
- Break up long lines

values: change default domain

---

charts/s3gw/questions.yaml

Rework questions.yaml incoorporating user feedback
- Ensure `example.com` is used as placeholder url where applicable
- Reorder and re-organize questions into sensible groups
- Utilize Rancher's builtin types where possible to generate drop-down menus of existing K8s objects instead of requiring text input. This applies to the storage class and secrets.
fixes: aquarist-labs/s3gw#341

rancher: rework questions.yaml

---

charts/s3gw/Chart.yaml

bump version to 0.15.0

---

charts/s3gw/questions.yaml
charts/s3gw/templates/NOTES.txt
charts/s3gw/templates/_helpers.tpl
charts/s3gw/templates/cosi-driver-deployment.yaml
charts/s3gw/templates/cosi-driver-secret.yaml
charts/s3gw/templates/cosi-rbac.yaml
charts/s3gw/templates/cosi-sa.yaml
charts/s3gw/values.yaml

add COSI support
Fixes: https://github.com/aquarist-labs/s3gw/issues/438
Fixes: https://github.com/aquarist-labs/s3gw/issues/436

add COSI support

---

charts/s3gw/Chart.yaml

charts: release v0.16.0

---

charts/s3gw/Chart.yaml

Release v0.17.0

---

charts/s3gw/Chart.yaml

Release v0.18.0

---

charts/s3gw/tests/cosi_test.yaml

Test the conditional creation of the various COSI resources:
- the ServiceAccount
- the ClusterRole and ClusterRoleBinding
Ensure the resources are created with unique names in the right namespaces.
Related-to: aquarist-labs/s3gw#518

tests: Test conditional creation of COSI resources

---

charts/s3gw/README.md

README.md: Say `helm repo add`, not `helm add repo`

---

charts/s3gw/Chart.yaml

Release v0.19.0

---

charts/s3gw/Chart.yaml
charts/s3gw/tests/cosi_test.yaml

Release v0.20.0

---

charts/s3gw/templates/_helpers.tpl
charts/s3gw/templates/certificate.yaml
charts/s3gw/templates/cosi-driver-deployment.yaml
charts/s3gw/templates/deployment.yaml
charts/s3gw/templates/ingress-traefik.yaml
charts/s3gw/templates/secret.yaml
charts/s3gw/templates/storage.yaml
charts/s3gw/templates/tests/smoke-bucket-create.yaml
charts/s3gw/templates/tls-issuer.yaml
charts/s3gw/templates/tls-secret.yaml
charts/s3gw/tests/cosi_test.yaml
charts/s3gw/tests/credentials_test.yaml
charts/s3gw/tests/deployment_test.yaml

add s3gw token to all s3gw's resource names
Fixes: https://github.com/aquarist-labs/s3gw/issues/630

add s3gw token to all s3gw's resource names

---

.github/workflows/lint.yaml
.github/workflows/test.yaml

Update Traefik helm repository

Update Traefik helm repository

---

charts/s3gw/Chart.yaml

Update release version to v0.21.0

Release v0.21.0

---

charts/s3gw/Chart.yaml

Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>

Release v0.22.0

---

.ct/chart_schema.yaml
.ct/lintconf.yaml
.gitignore
.pre-commit-config.yaml
Makefile
charts/s3gw/README.md
requirements-dev.txt
test-env/cluster-create.sh
test-env/cluster-prepare.sh
test-env/run-lint-test.sh

add support for lint and test locally
Fixes: https://github.com/aquarist-labs/s3gw/issues/677

add support for lint and test locally
