aquarist-labs/s3gw-charts

.github/workflows/lint-and-test.yaml, README.md, charts/s3gw/Chart.yaml, charts/s3gw/templates/tests/smoke-bucket-create.yaml
Add tests to the chart.
Helm tests are K8s jobs that Helm can utilize to determine if an
installation was successful. At the moment it is just a simple smoke
test, but in theory a full integration test can be implemented this way
as well.
Add some documentation to the readme. A short howto and explanation for
the options.
=> qa: add helm chart tests and readme text

CHANGELOG.md, README.md, charts/s3gw/Chart.yaml, charts/s3gw/values.yaml
- Traefik dependency has been removed
- Traefik installation option has been removed
Fixes: https://github.com/aquarist-labs/s3gw-charts/issues/12
=> Remove Traefik Dependency from chart

.github/workflows/lint-and-test.yaml, charts/s3gw/Chart.yaml, charts/s3gw/app-readme.md
This PR
- Adds an `app-readme` file with some information on the s3gw project for Rancher. 
- It also temporarily removes the maintainers' list. We don't want to have individual email addresses listed & we're in the process of getting a dedicated SUSE email address. We'll add the email address once we have access to it.
This PR references #14
Signed-off-by: Jesus Herman-Marina <jherman@suse.com>
=> Add app-readme for Rancher & remove maintainers

CHANGELOG.md, charts/s3gw/Chart.yaml, charts/s3gw/templates/configmap.yaml, charts/s3gw/values.yaml
small fixes for 0.2.0 release
- Defaulted access_key and secret_key fields to "test" in values.yaml
- Set imageTag to a specific version rather than using "latest"
- RGW_BACKEND_STORE property set to "sfs"
=> Small fixes

.gitignore, charts/s3gw/templates/configmap.yaml, charts/s3gw/values.yaml
- Configure UI to be able to access the S3GW RGW AdminOps API.
- Add hint how to workaround the CORS issue in the UI when using HTTPS and self-signed certificates.
=> Configure UI and add information about CORS.

.github/workflows/lint-and-test.yaml
Disable version checking by the linter for each PR.
This check is not necessary since we don't create a new chart release
after every PR.
=> linter: disable version check

.github/workflows/lint-and-test.yaml
Remove the traefik installation from the ci pipeline's install test
step. This is unnecessary since the chart no longer depends on traefik.
The ingress installation was never tested during this step, but the
installation of the traefik chart was still necessary since all
dependencies of a chart must be installed regardless of whether they are
used or not.
fixes: #68
=> ci: remove traefik installation from ci pipeline

charts/s3gw/templates/configmap.yaml
This flag will add more information to the response when a bucket is created. This information is needed by the UI to be able to link the new created bucket to the specified user.
Fixes: https://github.com/aquarist-labs/s3gw/issues/66
=> Set 'system' flag for default user

.github/workflows/lint-and-test.yaml, CHANGELOG.md, charts/s3gw/README.md, charts/s3gw/questions.yaml, charts/s3gw/templates/ingress-traefik.yaml, charts/s3gw/templates/secret.yaml, charts/s3gw/templates/tests/smoke-bucket-create.yaml, charts/s3gw/templates/ui-deployment.yaml, charts/s3gw/values.yaml
- Rename `enableIngress` to `ingress.enabled`.
- Introduce `hostnameNoTLS` values.
- Relocate xxxx_ui variables.
- Rename the `access_key` and `secret_key` variable names according the Helm Chart best practices guide to `accessKey` and `secretKey`.
- Defaulted `ui.enabled` to `true`.
Fixes: https://github.com/aquarist-labs/s3gw/issues/90
=> Various improvements.

.github/workflows/release.yaml
When 'main' branch changes, release the chart.
=> ci: release chart on push to main

charts/s3gw/Chart.yaml
Fix deprecated links to s3gw-core (now s3gw-tools) in chart description.
=> chart: fix links in chart description

charts/s3gw/templates/deployment.yaml
Fix the way image pull secrets are referenced in the deployment to allow pulling images from private registries
=> fix: image pull secret in deployment

CHANGELOG.md, charts/s3gw/templates/ingress-traefik.yaml
Fixes: https://github.com/aquarist-labs/s3gw/issues/170
=> No access to ETag property on response. Check CORS configuration to expose ETag header.

charts/s3gw/templates/ingress-traefik.yaml, charts/s3gw/values.yaml
Unify hostnames for TLS/non-TLS traffic. Theses two types of traffic will be separated by different ports.
=> ingress: unify hostnames

CHANGELOG.md, charts/s3gw/templates/ingress-traefik.yaml
Guessing the TLS certificate fails without explicitly configuring the wildcard host in the TLS section.
Before:
After:
=> Add wildcard host to tls section.

.github/workflows/release.yaml
Add manual trigger to release workflow to be able to force a release of the chart
=> ci: add manual release workflow trigger

CHANGELOG.md, charts/s3gw/templates/configmap.yaml, charts/s3gw/templates/deployment.yaml, charts/s3gw/templates/service.yaml
Note: developed on top of [cert-manager PR](https://github.com/aquarist-labs/s3gw-charts/pull/65)
- Internal TLS endpoint for the S3 service
- Configured the `s3gw` pod to accept TLS connections on port `7481`.
TLS Certificate and Key are mounted on pod's filesystem with a volume
from the `s3gw-cluster-ip-tls` secret.
- The `s3gw` ClusterIP service has been extended to link the s3gw pod port
`7481` with the service port `443`.
- Dropped some entries from `s3gw-config` map:
- `RGW_DNS_NAME`, `RGW_BACKEND_STORE`, `DEBUG_RGW`
- when applicable, these values are now taken directly from the chart.
Fixes: https://github.com/aquarist-labs/s3gw/issues/232
=> TLS endpoint on internal s3gw pod

charts/s3gw/templates/_helpers.tpl, charts/s3gw/values.yaml
Change the source of the container images to quay.io/s3gw
Related: https://github.com/aquarist-labs/s3gw/issues/176
=> registry: move to quay

.github/workflows/release.yaml, CHANGELOG.md, charts/s3gw/Chart.yaml
Bugfix release https://github.com/aquarist-labs/s3gw/issues/262
- Update images to v0.9.1
- Add release workflow trigger for pushes to release branches
=> release: v0.9.1

.github/workflows/release.yaml, CHANGELOG.md, charts/s3gw/Chart.yaml
Bugfix release https://github.com/aquarist-labs/s3gw/issues/262
- Update images to v0.9.1
- Add release workflow trigger for pushes to release branches
=> cherry-pick: release: v0.9.1

.github/workflows/release.yaml
Fix workflow definition syntax and only trigger on branches named 'v*'.
=> ci: fix releae workflow trigger

charts/s3gw/templates/certificate.yaml, charts/s3gw/templates/tls-issuer.yaml
Add missing labels to certificate management resources. This allows for clean upgrades and deinstallation when the chart has changed significantly or resources are moved between files between releases.
=> fix: add labels to certificate manager resources

.github/workflows/release.yaml
Change the base ref during version comparison of the release workflow. This allows changes to happen on main first and then be picked to a release branch without the linting step failing in the release pipeline.
Otherwise version bumps would need to happend first on the release branch and the be picked to the main branch, which is error prone and can get out of sync or be forgotten.
This way all changes happen on the main branch, then the relevant changes are picked to the release branch. The pipeline then compares the version in the Chart.yaml in whatever is pushed to the release branch to the version in the Chart.yaml at the previous HEAD of the release branch. If that version increased, the release pipeline will continue, thus avoiding accidental releases by pushing fixes to the …
=> ci: fix base ref for release workflow

CHANGELOG.md, charts/s3gw/questions.yaml, charts/s3gw/templates/NOTES.txt, charts/s3gw/templates/_helpers.tpl, charts/s3gw/templates/deployment.yaml, charts/s3gw/templates/secret.yaml, charts/s3gw/values.yaml
- Configuration options: `useExistingSecret` and `defaultUserCredentialsSecret`.
These fields allow the user to specify an existing secret containing
the S3 credentials for the default user.
- `useExistingSecret` is a boolean field defaulted to false.
- `defaultUserCredentialsSecret` is a string field denoting a `secret` in the `s3gw`
namespace. It must contain 2 keys:
- `RGW_DEFAULT_USER_ACCESS_KEY` that is the S3 Access Key for the default user.
- `RGW_DEFAULT_USER_SECRET_KEY` that is the S3 Secret Key for the default user.
- When `useExistingSecret` is set to `false`, the chart will create
the secret using values from the preexisting fields `accessKey` and `secretKey`.
- Setting `accessKey` or `secretKey` as the empty string, will force the Chart
to compute random alphanumeric values …
=> S3 credentials for default user via existing secret

charts/s3gw/templates/deployment.yaml
Specify the upgrade redeploy strategy, making sure it recreates the pods of the deployment rather than rolling out the upgrade. It is necessary to recreate the pods (i.e. delete the old pods and then create the new pods) rather than rolling out a new release (creating the new pods _before_ deleting the old pods), because the PVC is on ReadWriteOnce mode and thus the volume can only be claimed once by one pod.
fixes: aquarist-labs/s3gw#397
=> fix: upgrade redeploy strategy

charts/s3gw/templates/ingress-traefik.yaml
Fixes: https://github.com/aquarist-labs/s3gw/issues/410
The `accessControlExposeHeaders` property is set to `*` now to expose all headers by default. To fix the mentioned issue adding the `X-Amz-Object-Lock-Mode` and `X-Amz-Object-Lock-Retain-Until-Date` would be sufficient, but the problem might appear again in the future, but with a different header that is processed by the AWS SDK but is not exposed by the ingress.
=> The Traefik ingress is misconfigured, Access-Control-Expose-Headers must be set to '*'

charts/s3gw/Chart.yaml
- Add annotations for artifact hub detailing links for the home page and where to get support, as well as tagging the chart with the `storage` tag.
- Break up long lines in `Chart.yaml`
=> chart: add annotations for artifact hub

charts/s3gw/templates/deployment.yaml, charts/s3gw/values.yaml
Added two array fields in values.yaml
- `rgwCustomArgs`
- `rgwCustomEnvs`
With `helm install/update` you can specify custom arguments for the radosgw process using the `--set` option
`--set "rgwCustomArgs={--foo,bar,--color,green,--org,SUSE,--flag-param-foo}"`
With `helm install/update` you can specify custom environment variables for the radosgw process using the `--set` option
`--set "rgwCustomEnvs={ENV_1=ON,ENV_2=OFF,ENV_3}"`
Fixes: https://github.com/aquarist-labs/s3gw/issues/402
=> feat: custom args and custom env-vars for radosgw process

charts/s3gw/templates/configmap.yaml, charts/s3gw/templates/deployment.yaml
A no TLS / http configuration with
useCertManager = false and the TLS map not set
failed at two points:
- The UI's RGW_SERVICE_URL hard coded 'https'
- radosgw fails to start with invalid certificate config
Changes to support a http configuration:
ui.backendProtocol to control the protocol the UI speaks
with the S3GW backend.
No longer start a radosgw TLS frontend if neither cert manager, nor
the tls certificates are set up.
Signed-off-by: Marcel Lauhoff <marcel.lauhoff@suse.com>
=> Fix http / no TLS configuration

charts/s3gw/templates/_helpers.tpl, charts/s3gw/templates/storage.yaml, charts/s3gw/values.yaml
Cluster's default storage class can be specified with this combination of settings:
```
storageClass.create=false
storageClass.name=""
```
Note that this has always been the way the default storage class could be specified with the s3gw helm chart; the PR is restoring this behavior.
This mode now becomes the default for the charts.
Fixes: https://github.com/aquarist-labs/s3gw/issues/493
=> fix regression for default storage class

charts/s3gw/templates/_helpers.tpl, charts/s3gw/templates/cosi-driver-secret.yaml, charts/s3gw/values.yaml
Added chart option:
- cosi.driver.endpoint: it specifies the S3 endpoint url used by the COSI driver.
Default: {Release.Name}.{Release.Namespace}.{Values.privateDomain}
The field's value defaults with the 'http://' protocol scheme, eg: http://s3gw.s3gw.svc.cluster.local
Fixes: https://github.com/aquarist-labs/s3gw/issues/511
=> fix unsupported protocol scheme issue when COSI driver connects to rgw

.github/workflows/lint.yaml
Upgrade Kind version and let it track the latest of th v1.x.y release series. This should avoid trouble with pinning the Kind version to something that only supports a very old version of the Kubernetes API
=> ci: upgrade Kind version

charts/s3gw/templates/chart-validation.yaml, charts/s3gw/templates/tls-issuer.yaml
When using the Letsencrypt TLS issuer, a valid email address (the one of the account requesting the certificate) is required in the .email field of the values.yaml.
This change introduces a templating check that fails the installation of the s3gw if the letsencrypt issuer is to be used with the default (invalid) email, reminding the user to set a valid one. It also avoids deploying both the self-signed and letsencrypt issuers at the same time. In case the self-signed issuer is desired it unnecessary to deploy the letsencrypt issuer as well and with no valid email given (which isn't necessary for the self signed issuer), the letsencrypt issued would not deploy successfully.
Fixes: aquarist-labs/s3gw#596
=> chart: validate email for tls issuer

charts/s3gw/templates/chart-validation.yaml
When publicDomain field is empty charts intallation must fail only if ingress.enabled = true.
When ingress.enabled = false, publicDomain field is ignored.
Fixes: https://github.com/aquarist-labs/s3gw/issues/602
=> fix installation failure when publicDomain is empty

charts/s3gw/tests/validation_test.yaml
The chart-validataion template checks that non-sensical values provided during upgrade or installation fail early with an appropriate error message.
- Add unittests covering the various cases checked in the chart-validation template
=> ci: Improved unit testing for chart-validation

charts/s3gw/templates/cosi-driver-secret.yaml, charts/s3gw/tests/cosi_test.yaml
- Use the generated secret/access key pair in the COSI driver secret, when no keys are explicitly given.
- Add tests ensuring the correct generation of the manifest for the COSI driver secret.
=> fix: use generated key pair for COSI

.github/workflows/test.yaml, charts/s3gw/templates/chart-validation.yaml, charts/s3gw/tests/credentials_test.yaml, charts/s3gw/tests/deployment_test.yaml, charts/s3gw/tests/validation_test.yaml
Enable the `--strict` command line option for the Helm Unittest plugin. This option causes the unittest suites to be evaluated against their schema and potential typos are considered failures. Otherwise typos in the test suites may cause tests to be silently ignored or other silent behavior change without necessarily causing a failure.
See: https://github.com/helm-unittest/helm-unittest/issues/178
=> ci: Run `helm unittest` in strict mode

charts/s3gw/templates/configmap.yaml
Adds a new configmap entry, pointing to the address of the s3gw service.
This will be consumed by the `s3gw-ui` backend.
We are leaving the original entry in there nonetheless so we don't break the UI if/when this gets merged, depending on whether changed to the UI get merged before or after. It should be removed in a coming release.
=> charts/configmap: add S3GW_SERVICE_URL

charts/s3gw/templates/NOTES.txt, charts/s3gw/templates/chart-validation.yaml, charts/s3gw/tests/validation_test.yaml
- Append the https:// protocol to the displayed URLs. Since the chart always installs the TLS certificates, we can restrict the output URLs to HTTPS.
- Add more chart validation tests.
=> Several improvements to the chart

charts/s3gw/questions.yaml, charts/s3gw/templates/deployment.yaml, charts/s3gw/values.yaml
By using a wrapper script as the container entrypoint, we abstract how arguments to the underlying radosgw binary are passed. Instead, pass arguments known by the script, and let it do what is best.
(cherry picked from commit ce35341643929258794eac2cb622622436fad45b)
=> charts/deployment: adjust for wrapper script (backport)

charts/s3gw/Chart.yaml, charts/s3gw/questions.yaml, charts/s3gw/templates/deployment.yaml, charts/s3gw/values.yaml
By using a wrapper script as the container entrypoint, we abstract how arguments to the underlying radosgw binary are passed. Instead, pass arguments known by the script, and let it do what is best.
This pull request has a companion pull request in aquarist-labs/s3gw#758 .
Also, this patchset also releases v0.23.0.
=> charts/deployment: adjust for wrapper script and release v0.23.0
